### ISSUE TITLE
Black artifacts on image

### ISSUE THREAD

**Issue by NSQY** [AmusementClub/vs-bmdegrain#1]
Hi, you're probably already aware of this but I thought it prudent to report anyway;

With default settings, on GRAYS, RGBS, or YUV4xxPS clips, black artifacts can be observed: https://slow.pics/c/bCzJhiYM

Checked GCC (gcc version 12.2.1 20230111 (GCC)), clang (clang version 15.0.7), and the github artifact on Linux.

**Comment by WolframRhodium** [comment]
Thanks. https://github.com/AmusementClub/vs-bmdegrain/commit/e2250adaff51eb16c9f8386f62776f8cf99ac3e3 should solve it.

**Comment by NSQY** [comment]
Working now, thanks
